######################################################################
# Automatically generated by qmake (2.01a) ?? 3. ??? 12:19:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Course_work.h Solver.h VYRAZ.h
SOURCES += Course_work.cpp main.cpp Solver.cpp VYRAZ.cpp
